

networks:
  printnet:  # Now managed by Docker Compose
    name: printnet  # Force the exact name to prevent prefixing
    driver: bridge  # Standard bridge network


services:
  directprintclient:
    build: ./direct_print
    container_name: directprintclient
    restart: unless-stopped
    environment:
      - CUPS_USER_ADMIN=admin
      - CUPS_USER_PASSWORD=adminpassword
      - CUPS_WEBINTERFACE=yes
    volumes:
      - ./cups_data:/etc/cups  # Mount CUPS configuration
      - ./printers:/var/spool/cups  # Mount print queue
      - ./cups_data/cupsd.conf:/etc/cups/cupsd.conf  # Override cupsd.conf
    ports:
      - "8888:8888"
      - "631:631"
    networks:
      - printnet  # Attaches to printnet



  samba:
    build: ./samba
    container_name: samba
    restart: unless-stopped
    environment:
      - USERNAME=printuser
      - PASSWORD=printpassword
    volumes:
      - ./printers:/printers
    ports:
      - "139:139"
      - "1445:445"
    networks:
      - printnet  # Attaches to printnet
