  GNU nano 7.2                                                                    smb.conf                                                                              [global]
   workgroup = WORKGROUP
   printing = CUPS
   printcap name = cups
   load printers = yes

[printers]
   comment = All Printers
   path = /var/spool/samba
   printable = yes
   guest ok = yes
   browseable = yes