[global]
   workgroup = WORKGROUP
   server string = Samba Print Server
   security = user
   map to guest = Bad User
   guest account = nobody
   printing = cups
   printcap name = cups
   load printers = yes
   cups options = raw
   log file = /var/log/samba/log.%m
   max log size = 50
   dns proxy = no
   disable spoolss = no


[printers]
   comment = All Printers
   path = /var/spool/samba
   browseable = yes
   guest ok = yes
   writable = no
   printable = yes
   create mode = 0700
   cups options = raw


[print$]
   comment = Printer Drivers
   path = /var/lib/samba/printers
   browseable = yes
   guest ok = no
   read only = no
   write list = root, @lpadmin
