# Subscription configuration file for CUPS v2.3.3op2
# Written by cupsd
NextSubscriptionId 6
<Subscription 1>
Events all
Owner root
Recipient rss://zd420-office
PrinterName zd420-office
LeaseDuration 0
Interval 0
ExpirationTime 0
NextEventId 4
</Subscription>
<Subscription 2>
Events all
Owner root
Recipient rss://zpl420
PrinterName zpl420
LeaseDuration 0
Interval 0
ExpirationTime 0
NextEventId 4
</Subscription>
<Subscription 3>
Events printer-changed
Owner root
LeaseDuration 86400
Interval 60
ExpirationTime 1741701319
NextEventId 1
</Subscription>
<Subscription 4>
Events printer-changed
Owner root
LeaseDuration 86400
Interval 60
ExpirationTime 1741701354
NextEventId 1
</Subscription>
<Subscription 5>
Events printer-changed
Owner root
LeaseDuration 86400
Interval 60
ExpirationTime 1741702007
NextEventId 1
</Subscription>
